Program N8_ALEJANDRO;

USES BIBLIONT;

CONST CARGOS:ARRAY [1..12] OF STRING[22]=
('ENGANADOR DE CHEFE    ','ENROLADOR DE TRABALHO ','PENSADOR              ','ANALISTA DE SISTEMAS  ',
 'DEGUSTADOR DE CERVEJA ','TECNICO EM REDES      ','CONTADOR DE ESTORIAS  ','PEDREIRO DE PRIMEIRA  ',
 'ACOUGUEIRO LIMPINHO   ','SEGURANCA DE BANHEIRO ','GESTOR DE BORBOLETAS  ','AGENTE LEVA E TRAZ    ' );

VAR ARQ : FILE OF REGIS;
    REG:REGIS;
    REGD:REGIS;
    VET:VETOR;
    CA:STRING[2]; NUME: STRING[4];
    A,B,C,T,OPC,E,IND,CONTLIN,ANTERIOR,ORDE:INTEGER;
    TOTCAR:ARRAY[1..12] OF INTEGER;
//***************************************************************************************************
BEGIN
 ASSIGN(ARQ,'CAND.IND');
 RESET(ARQ);
 WRITELN('ENTRE COM A OPCAO:');
 WRITELN('1-PARA MOSTRAR EM ORDEM DE INSCRICAO');
 WRITELN('2-PARA MOSTRAR EM ORDEM DE ALFABETICA');
 WRITELN('3-PARA MOSTRAR EM ORDEM DE CPF');
 WRITELN('4-PARA MOSTRAR EM ORDEM DE CARGO E ALFABETICO DENTRO DO CARGO'); 
 REPEAT
  LEIA1('ORDEM',OPC);       		
 UNTIL(OPC>=0) AND (OPC<=4);
//LEIO O ARQUIVO DO PRIM AO ULT REGISTRO PARA MONTAR O VETOR DE INDICE
 REPEAT
  READ(ARQ,REG);
  IND:=A+1;
  VET[IND].PF:=A;
	IF(OPC=4)THEN
//MONTA O CAMPO CHAVE PARA O VETOR (CC) CARGO E NOME  NO VETOR
	 BEGIN
	  VET[IND].CC:=REG.NOME;			//COLOCA O NOME NO CC DO VETOR
	  STR(REG.CAR,CA);  					//TRANSFORMA O CARGO DE INTEGER PARA STRING[2]
	  IF(REG.CAR<10)THEN
	   INSERT('0',CA,1);					//INSERE '0' NOS CARGOS MENORES QUE 10. EX. 3, FICA 03 -- 11, FICA 11
	  INSERT(CA,VET[IND].CC,1);		//INSERE O CARGO NA FRENTE DO CC DO VETOR. EX. CC='PEDRO BOM', CARGO=3, FICA CC=03PEDRO BOM
	 END
	ELSE
	 IF(OPC=3)THEN
    VET[IND].CC:= REG.CPF
	 ELSE
    IF(OPC=2) THEN
     VET[IND].CC:= REG.NOME
	  ELSE  // if opc = 1
	  BEGIN
	   STR(REG.NUM,NUME);
	   T:= LENGTH(NUME);
	   FOR C:= 1 TO 4-T DO
	    INSERT('0',NUME,1);
	   VET[IND].CC:= NUME;
		END;      
	A:=A+1;
 UNTIL(EOF(ARQ));
 // ind = 1227
//FIM DA MONTAGEM DO VETOR DE ACORDO COM A OPCAO
//******************************************************************************************************
  FOR E:=1 TO 15 DO
	 WRITELN(VET[E].PF:5,' ',VET[E].CC);  	//MOSTRA OS 15 PRIMEIROS ELEMENTOS DO VETOR ANTES DE ORDENAR
	WRITELN('ORDENANDO....');

	ORDEM(VET,IND);

	WRITELN('FIM DA ORDENA�AO');
  FOR E:=1 TO 15 DO
	 WRITELN(VET[E].PF:5,' ',VET[E].CC);		//MOSTRA OS 15 PRIMEIROS ELEMENTOS DO VETOR DEPOIS DE ORDENADO
	WRITELN('=============ENTER PARA CONTINUAR===================');
//********************************************************************************************************
	FOR E:= 1 TO IND DO 										//PARA LER DO PRIMEIRO AO ULTIMO, IND = 1227
	 BEGIN
	  SEEK(ARQ,VET[E].PF); 								//ANTES DE LER, POSICIONA DE ACORDO COM O CAMPO PF DO VETOR ORDENADO PELO CC
	  READ(ARQ,REG);
	  TOTCAR[REG.CAR]:=TOTCAR[REG.CAR]+1;		//CONTA NUMERO DE INSCRITOS POR CARGO
    IF(OPC=4) AND (ANTERIOR <> REG.CAR) THEN
     ORDE:=0;                             //INICIALIZA O CONTADOR DE LINHAS APRESENTADAS
//ANTES DE MOSTRAR A LINHA COM AS INFORMA�OES DO REGISTRO VERIFICA AS CONDICOES PARA IMPRESSAO DO CABECALHO
	  IF((CONTLIN MOD 25=0) OR ((OPC=4) AND (ANTERIOR <> REG.CAR))) THEN
//IMPRIME O CABECALHO SE: CONTADOR DE LINHAS = 25 OU
//SE OPCAO FOR 4 E O CARGO LIDO FOR DIFERENTE DO MOSTRADO ANTERIORMENTE
	   BEGIN                     
	    READLN; // **fica esperando enter para mudar de telaS                     
	    CLRSCR;
	    ANTERIOR:=REG.CAR; 								//ATUALIZA O CARGO ANTERIOR
	    WRITELN;
	    IF(OPC=4)THEN      								//SE OPCAO FOR 4 MOSTRA O NOME DO CARGO
	     WRITELN(ANTERIOR:5,' -- ',CARGOS[ANTERIOR]);
      write('  ORD  NUM N O M E                             ===C P F=== NASCIMENTO CS  N1');
      WRITELN('  N2  N3  N4  N5  N6  SO   CG  CC CV');
      CONTLIN:=0;
	   END;
//FIM DA IMPRESSAO DO CABECALHO
    ORDE:=ORDE+1;  																			//CONTADOR DE LINHAS IMPRESSAS
		WRITE(ORDE:5,REG.NUM:5,' ',REG.NOME,' ',REG.CPF,' ',REG.DATA.DIA,'/',REG.DATA.MES,'/',REG.DATA.ANO,REG.CAR:3); //DADOS INICIAIS
		FOR A:=1 TO 6 DO
		 WRITE(REG.NOTAS[A]:4); 														//MOSTRA NOTAS
		WRITELN(REG.SOM:4,REG.CLG:5,REG.CLC:4,REG.CCL:3);		//MOSTRA CAMPOS SOMA E DE CLASSIFICA��O
		CONTLIN:=CONTLIN+1;
	 END;
	CLOSE(ARQ);
	WRITELN;
	WRITELN;
	WRITELN('TOTAL DE INSCRITOS POR CARGO');
	FOR A:=1 TO 12 DO
	 WRITELN(A:3,' -- ',CARGOS[A],' -->',TOTCAR[A]:4);
	TERMINE;	 
End.